http://market-tracker.chrispiserchia.com {
    handle /api/ai/* {
        reverse_proxy localhost:8788
    }
    handle_path /stocks/* {
        reverse_proxy localhost:8788
    }
    handle /api/crypto/* {
        reverse_proxy localhost:8789
    }
    handle_path /crypto/* {
        reverse_proxy localhost:8789
    }
    handle {
        reverse_proxy localhost:8787
    }
}
