#!/usr/bin/env bash
# scripts/setup-caddy.sh — install Caddy and create the base config.
#
# Usage:
#   bash scripts/setup-caddy.sh
#
# Idempotent: safe to re-run. Overwrites Caddyfile if domain changed.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
LOG_DIR="$PROJECT_DIR/volumes/logs"

# ── Check dependency ──────────────────────────────────────────────────────
command -v caddy >/dev/null || brew install caddy

# ── Load domain ───────────────────────────────────────────────────────────
DOMAIN=$(grep -E '^SERVER_DOMAIN=' "$PROJECT_DIR/.env" | cut -d'=' -f2)
[[ -n "$DOMAIN" ]] || { echo "ERROR: Set SERVER_DOMAIN in .env first"; exit 1; }

echo "=== Caddy Setup ==="
echo "  Domain:  $DOMAIN"
echo "  Config:  $PROJECT_DIR/Caddyfile"
echo ""

# ── Create Caddyfile ──────────────────────────────────────────────────────
mkdir -p "$PROJECT_DIR/Caddyfile.d" "$LOG_DIR"

cat > "$PROJECT_DIR/Caddyfile" <<EOF
{
    admin localhost:2019
}

# Dashboard at apex and dashboard subdomain
http://$DOMAIN, http://dashboard.$DOMAIN {
    reverse_proxy localhost:8080
}

# Per-project snippets (generated by register-project.sh)
import Caddyfile.d/*.conf
EOF

echo "  Caddyfile written"

# ── Install Caddy as a launchd service ────────────────────────────────────
CADDY_BIN="$(which caddy)"
PLIST_PATH="$HOME/Library/LaunchAgents/com.assistant.caddy.plist"

cat > "$PLIST_PATH" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.assistant.caddy</string>
  <key>ProgramArguments</key>
  <array>
    <string>$CADDY_BIN</string>
    <string>run</string>
    <string>--config</string>
    <string>$PROJECT_DIR/Caddyfile</string>
  </array>
  <key>WorkingDirectory</key>
  <string>$PROJECT_DIR</string>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>StandardOutPath</key>
  <string>$LOG_DIR/caddy.out.log</string>
  <key>StandardErrorPath</key>
  <string>$LOG_DIR/caddy.err.log</string>
</dict>
</plist>
PLIST

launchctl unload "$PLIST_PATH" 2>/dev/null || true
launchctl load -w "$PLIST_PATH"

echo "  Caddy service installed and started"
echo ""
echo "=== Caddy setup complete ==="
echo "  Caddyfile:    $PROJECT_DIR/Caddyfile"
echo "  Per-project:  $PROJECT_DIR/Caddyfile.d/"
echo "  Plist:        $PLIST_PATH"
echo ""
echo "Verify:"
echo "  launchctl list | grep com.assistant.caddy"
echo "  curl -k https://localhost/"
